### ISSUE TITLE
REFRESH_INTERVAL instructions

### ISSUE THREAD

**Issue by plittlefield** [jbbodart/gandi-livedns#5]
Hi,

Great container, thank you very much for making it :)

You need to make a small tweak to the documentation.

From ...

_REFRESH_INTERVAL: Delay between updates (default: 10mn)_

To ...

_REFRESH_INTERVAL: Delay between updates (default: 10m).  This uses the Linux sleep command with a valid NUMBER and SUFFIX.  SUFFIX  may be 's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days.  For example, 10m for 10 minutes._

Regards,

Paully

**Comment by jbbodart** [comment]
Hello,

Thank you. I have changed the documentation a bit.
I want to keep it simple, advanced users who can dig into the code can use sleep suffixes ;)

Regards
jb
