### ISSUE TITLE
DNS update returns 403 error - API keys depricated

### ISSUE THREAD

**Issue by erkston** [jbbodart/gandi-livedns#6]
Gandi has depricated API keys in favor of Personal Access Tokens (PATs)
https://api.gandi.net/docs/authentication/

The API URL has also changed to https://api.gandi.net/v5/livedns

**Comment by G-eos** [comment]
Discussion on going here to fix ddclient. Which will do the job: https://github.com/ddclient/ddclient/issues/602

**Comment by G-eos** [comment]
I try to build a fix, but not have time to test it. See the PR  https://github.com/jbbodart/gandi-livedns/pull/7

**Comment by jbbodart** [comment]
Hello,
Thank you very much. I merged your fix :)
